# Generated by Django 4.0.4 on 2022-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
