# Generated by Django 4.0.4 on 2022-04-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_feature_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tag_id',
            new_name='tags',
        ),
    ]
