# Generated by Django 4.0.4 on 2022-04-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_category_id_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_access',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
